routes/web.php
<?php
//client routes
Route::get('/', 'MainPageController@index');

Route::post('/defer/add', 'ProductDeferController@addDeferred');
Route::post('/defer/send', 'ProductDeferController@sendForm');
Route::post('/defer/delete_all', 'ProductDeferController@deleteAll');
Route::get('/defer/delete', 'ProductDeferController@delete');
Route::get('/defer', 'ProductDeferController@defer');

Route::get('news', 'NewsController@showForClient');
Route::get('news/{news}', 'NewsController@showOneForClient');

Route::get('dizajn', 'DesignStudioController@showPage');

//catalog
Route::get('catalog', 'CatalogController@index')->name('catalog.index');
Route::get('catalog/{first}', 'CatalogController@firstLevel');
Route::get('catalog/{first}/{second}', 'CatalogController@secondLevel');
Route::get('catalog/{first}/{second}/{third}', 'CatalogController@thirdLevel');
Route::get('catalog/{first}/{second}/{third}/{product}', 'CatalogController@showProduct');


//ajax calls
Route::group(['prefix' => 'ajax',], function () {
    Route::post('/subscribe', 'SubscriberController@store');
    Route::post('/contact', 'CallbackController@makeFromAjax');
});

//admin login
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('logout', 'Auth\LoginController@logout');
    Auth::routes();
});

//admin routes
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'ClientMenuController@index');

    Route::post('menu/order', 'ClientMenuController@updateOrder')->name('menu.order');
    Route::resource('menu', 'ClientMenuController');

    Route::get('contacts/edit', 'ContactsController@edit')->name('contacts.edit');
    Route::post('contacts/update', 'ContactsController@update')->name('contacts.update');

    Route::get('interior/edit', 'InteriorController@edit')->name('interior.edit');
    Route::post('interior/update', 'InteriorController@update')->name('interior.update');

    Route::get('news/copy/{id}', 'NewsController@copy')->name('news.copy');
    Route::post('news/order', 'NewsController@updateOrder')->name('news.order');
    Route::resource('news', 'NewsController');

    Route::post('photos/ajax', 'PhotosController@uploadAjax');
    Route::post('photos/deleteMulti', 'PhotosController@destroyMulti')->name('photos.delete.multi');
    Route::resource('photos', 'PhotosController');

    Route::any('ajax/imageUpload', 'PhotosController@uploadAjax');
    Route::any('ajax/searchPhoto', 'PhotosController@searchAjax');

    Route::resource('slider', 'Admin\SliderController');
    Route::post('slider/order', 'Admin\SliderController@updateOrder')->name('slider.order');

    Route::resource('info_page', 'InfoPageController');
    Route::resource('meta_data', 'MetaDataController');

    Route::resource('subscriber', 'SubscriberController');

    Route::resource('product', 'ProductController');

    Route::resource('category', 'CategoryController');
    Route::post('category/order', 'CategoryController@updateOrder')->name('category.order');

    Route::resource('order', 'OrderController');

    Route::resource('callback', 'CallbackController');

    Route::post('brand/order', 'BrandController@updateOrder')->name('brand.order');
    Route::resource('brand', 'BrandController');

    Route::group(['prefix' => 'settings'], function () {
        Route::put('settings/offer/update','Admin\Settings\SpecialOfferController@update')->name('settings.offer.update');
        Route::get('settings/offer/edit','Admin\Settings\SpecialOfferController@edit')->name('settings.offer.edit');

    });

    Route::resource('design_studio', 'DesignStudioController');

});

Route::get('/{any}', 'PageController@index')->where('any', '(.*)');

resources/views/admin/app.blade.php
@include('admin.head')
<body>

@include('admin.nav.main')

@if (!Auth::guest())
    @include('admin.menu')
@endif

<div class="container-fluid b-content">
    @include('flash::message')
    @include('partials.errors')
    @yield('content')
</div>

<script src="{{ asset('admin_assets/js/app_footer.js') }}"></script>

</body>
</html>

resources/views/admin/head.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- Styles -->
    <link href="{{ asset('admin_assets/css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('admin_assets/css/temp.css') }}" rel="stylesheet">
    <script src="{{ asset('admin_assets/js/libs.js') }}"></script>
    <script src="{{ asset('admin_assets/js/app.js') }}"></script>
    <script src="{{asset('admin_assets/js/tinymce/tinymce.min.js')}}"></script>
</head>

resources/views/admin/menu.blade.php
<div id="sidebar">
    <nav class="navbar navbar-inverse navbar-fixed-top b-menu_wrapper">
        <ul class="nav sidebar-nav">
            <li class="sidebar-brand">
                <a href="{{ url('/') }}">
                    {{ config('app.name') }}
                </a>
            </li>

            <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Главная страница
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{{route('menu.index')}}">Меню</a></li>
                    <li><a href="{{route('brand.index')}}">Брэнды</a></li>
                    <li><a href="{{route('contacts.edit')}}">Контакты</a></li>
                    <li><a href="{{route('interior.edit')}}">Дизайн интерьера</a></li>
                </ul>
            </li>

            <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Страницы <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    {{--<li class="dropdown-header">Заглавие подраздела</li>--}}
                    <li><a href="{{route('info_page.index')}}">Инф. страницы</a></li>
                    <li><a href="{{route('meta_data.index')}}">Метаданные</a></li>
                    <li><a href="{{route('design_studio.index')}}">Дизайн студия</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Слайдеры <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{{route('slider.index', ['slider'=>'main'])}}">Слайдер в шапке</a></li>
                    <li><a href="{{route('slider.index', ['slider'=>'interior'])}}">Слайдер интерьеры</a></li>
                    <li><a href="{{route('slider.index', ['slider'=>'about_us'])}}">Слайдер про нас</a></li>
                </ul>
            </li>

            <li>
                <a href="{{route('news.index')}}">Новости</a>
            </li>

            <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Галерея
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{{route('photos.index')}}">Все фото</a></li>
                    <li><a href="{{route('photos.create')}}">Добавить</a></li>
                </ul>
            </li>

            <li>
                <a href="{{route('subscriber.index')}}">Подписчики</a>
            </li>

            <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Каталог
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{{route('product.index')}}">Товары</a></li>
                </ul>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{{route('category.index')}}">Категории</a></li>
                </ul>
            </li>

            <li>
                <a href="{{route('order.index')}}">Заказы</a>
            </li>

            <li>
                <a href="{{route('callback.index')}}">Обратная связь</a>
            </li>

            <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Настройки
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{{route('settings.offer.edit')}}">Акция</a></li>
                </ul>
            </li>


        </ul>
        <button type="button" class="b-sidebar__btn is-closed" >
            <span class="hamb-top"></span>
            <span class="hamb-middle"></span>
            <span class="hamb-bottom"></span>
        </button>
    </nav>
</div>