routes/web.php
<?php
//client routes
Route::get('/', 'MainPageController@index');

Route::post('/defer/add', 'ProductDeferController@addDeferred');
Route::post('/defer/send', 'ProductDeferController@sendForm');
Route::post('/defer/delete_all', 'ProductDeferController@deleteAll');
Route::get('/defer/delete', 'ProductDeferController@delete');
Route::get('/defer', 'ProductDeferController@defer');

Route::get('news', 'NewsController@showForClient');
Route::get('news/{news}', 'NewsController@showOneForClient');

Route::get('dizajn', 'DesignStudioController@showPage');

//catalog
Route::get('catalog', 'CatalogController@index')->name('catalog.index');
Route::get('catalog/{first}', 'CatalogController@firstLevel');
Route::get('catalog/{first}/{second}', 'CatalogController@secondLevel');
Route::get('catalog/{first}/{second}/{third}', 'CatalogController@thirdLevel');
Route::get('catalog/{first}/{second}/{third}/{product}', 'CatalogController@showProduct');


//ajax calls
Route::group(['prefix' => 'ajax',], function () {
    Route::post('/subscribe', 'SubscriberController@store');
    Route::post('/contact', 'CallbackController@makeFromAjax');
});

//admin login
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('logout', 'Auth\LoginController@logout');
    Auth::routes();
});

//admin routes
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'ClientMenuController@index');

    Route::post('menu/order', 'ClientMenuController@updateOrder')->name('menu.order');
    Route::resource('menu', 'ClientMenuController');

    Route::get('contacts/edit', 'ContactsController@edit')->name('contacts.edit');
    Route::post('contacts/update', 'ContactsController@update')->name('contacts.update');

    Route::get('interior/edit', 'InteriorController@edit')->name('interior.edit');
    Route::post('interior/update', 'InteriorController@update')->name('interior.update');

    Route::get('news/copy/{id}', 'NewsController@copy')->name('news.copy');
    Route::post('news/order', 'NewsController@updateOrder')->name('news.order');
    Route::resource('news', 'NewsController');

    Route::post('photos/ajax', 'PhotosController@uploadAjax');
    Route::post('photos/deleteMulti', 'PhotosController@destroyMulti')->name('photos.delete.multi');
    Route::resource('photos', 'PhotosController');

    Route::any('ajax/imageUpload', 'PhotosController@uploadAjax');
    Route::any('ajax/searchPhoto', 'PhotosController@searchAjax');

    Route::resource('slider', 'Admin\SliderController');
    Route::post('slider/order', 'Admin\SliderController@updateOrder')->name('slider.order');

    Route::resource('info_page', 'InfoPageController');
    Route::resource('meta_data', 'MetaDataController');

    Route::resource('subscriber', 'SubscriberController');

    Route::resource('product', 'ProductController');

    Route::resource('category', 'CategoryController');
    Route::post('category/order', 'CategoryController@updateOrder')->name('category.order');

    Route::resource('order', 'OrderController');

    Route::resource('callback', 'CallbackController');

    Route::post('brand/order', 'BrandController@updateOrder')->name('brand.order');
    Route::resource('brand', 'BrandController');

    Route::group(['prefix' => 'settings'], function () {
        Route::put('settings/offer/update','Admin\Settings\SpecialOfferController@update')->name('settings.offer.update');
        Route::get('settings/offer/edit','Admin\Settings\SpecialOfferController@edit')->name('settings.offer.edit');

    });

    Route::resource('design_studio', 'DesignStudioController');

});

Route::get('/{any}', 'PageController@index')->where('any', '(.*)');

app/Http/Controllers/ClientMenuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Menu;

class ClientMenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = (new Menu)->getFirstLevel();
        return view('admin.client_menu.list', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.client_menu.create');
    }

    /**
     * Save menu item
     *
     * @param  \Illuminate\Http\Request $request
     * @param Menu $menu
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request, Menu $menu)
    {
        $this->validate($request, [
            'item_name' => 'required',
            'url'       => 'required',
        ]);

        $last_item = $menu->getLastItem() ? $menu->getLastItem()->order_num : 0;
        $menu->order_num = $last_item + 1;
        $menu->fill($request->all());
        $menu->save();

        return $this->redirectSuccessWithMsg('Пункт меню удачно создан');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Menu::find($id);

        $menu = new Menu;

        return view('admin.client_menu.edit', compact('item', 'menu'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $item = Menu::findOrFail($id);
        $item->fill($request->all());
        $item->save();

        return $this->redirectSuccessWithMsg('Пункт меню удачно обновлен');
    }

    /**
     * Remove the specified menu item
     *
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        Menu::destroy($id);

        return $this->redirectSuccessWithMsg('Пункт меню удален');
    }


    /**
     * Update the order of items in the menu
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function updateOrder()
    {
        $menu = Menu::all();
        $counter = 1;

        if (request()->has('item_id')) {
            foreach (request()->item_id as $index => $new_menu) {
                foreach ($menu as $current_menu) {
                    if ($current_menu->id == $index) {
                        $current_menu->order_num = $counter;
                        $current_menu->save();
                        $counter++;
                    }
                }
            }
        }

        return $this->redirectSuccessWithMsg('Порядок изменен');

    }

    /**
     * Redirect with success message.
     *
     * @param $msg
     * @param string $route
     * @return \Illuminate\Http\RedirectResponse
     */
    public function redirectSuccessWithMsg($msg, $route = 'menu.index')
    {
        flash($msg)->important();

        return redirect()->route($route);

    }
}

resources/views/admin/client_menu/create.blade.php
@extends('admin.app')
@inject('menu', '\App\Models\Menu')

@section('content')
    <div class="panel panel-default b-main-menu">
        <div class="panel-heading">Создать пункт в меню</div>

        <div class="panel-body">
            <form method="POST"
                  class="col-lg-6 col-md-6 col-sm-6 col-xs-6"
                  action="{{route('menu.store')}}">
                <div class="form-group">
                    <label for="item_name">Заглавие</label>
                    <input type="text" name="item_name" id="item_name" class="form-control" value="{{ old('item_name') }}">
                </div>
                <div class="form-group">
                    <label for="url">Адрес</label>
                    <input type="text" name="url" id="url" class="form-control" value="{{ old('url') }}">
                </div>

                <div class="form-group">
                    <label for="parent_id">Родительский раздел</label>
                    <select name="parent_id" id="parent_id" class="form-control">
                        <option value="0">Нет родительского раздела</option>
                        @foreach($menu->getFirstLevel() as $first)
                            <option value="{{$first->id}}">
                                {{$first->item_name}}
                            </option>
                            @if ($first->getChildren($first->id))
                                @foreach($first->getChildren($first->id) as $second)
                                    <option value="{{$second->id}}">
                                        &nbsp;&nbsp;{{$second->item_name}}
                                    </option>
                                @endforeach
                            @endif
                        @endforeach
                    </select>
                </div>


                {{csrf_field()}}

                <button type="submit"  class="btn btn-default">Создать</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/client_menu/edit.blade.php
@extends('admin.app')

@section('content')
    <div class="panel panel-default b-main-menu">
        <div class="panel-heading">Редактировать пункт в меню</div>

        <div class="panel-body">
            <form method="POST"
                  class="col-lg-6 col-md-6 col-sm-6 col-xs-6"
                  action="{{route('menu.update', $item->id)}}">
                <div class="form-group">
                    <label for="item_name">Заглавие</label>
                    <input type="text" name="item_name" id="item_name" class="form-control"
                           value="{{ $item->item_name }}">
                </div>
                <div class="form-group">
                    <label for="url">Адрес</label>
                    <input type="text" name="url" id="url" class="form-control" value="{{ $item->url }}">
                </div>

                <div class="form-group">
                    <label for="parent_id">Родительский раздел</label>
                    <select name="parent_id" id="parent_id" class="form-control">
                        <option value="0">Нет родительского раздела</option>
                        @foreach($menu->getFirstLevel() as $first)
                            <option value="{{$first->id}}"
                                    {{$item->parent_id == $first->id ? ' selected ': '' }}
                                    {{$item->id == $first->id ? ' disabled ': '' }}>
                                {{$first->item_name}}
                            </option>
                            @if ($first->getChildren($first->id))
                                @foreach($first->getChildren($first->id) as $second)
                                    <option value="{{$second->id}}"
                                            {{$item->parent_id == $second->id ? ' selected ': '' }}
                                            {{$item->id == $second->id ? ' disabled ': '' }}>
                                        &nbsp;&nbsp;{{$second->item_name}}
                                    </option>
                                @endforeach
                            @endif
                        @endforeach
                    </select>
                </div>

                {{csrf_field()}}
                {{method_field('PUT')}}

                <button type="submit" class="btn btn-default">Обновить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/client_menu/list.blade.php
@extends('admin.app')
{{--@inject('menu', '\App\Models\Menu')--}}

@section('content')
    <div class="panel panel-default b-menu">
        <div class="panel-heading">Главное меню</div>

        <div class="panel-body">
            <div class="b-menu_btn">
                <form method="GET" action="{{route('menu.create')}}" class="form-inline">
                    <button type="submit" class="btn btn-primary">Создать раздел меню</button>
                </form>
                <form method="POST" action="{{route('menu.order')}}" class="form-inline b-menu_btn__order">
                    {{csrf_field()}}
                    <button type="submit" class="btn btn-primary">Сохранить порядок пунктов</button>
                </form>
            </div>

            <div class="text-muted small">
                Перетащите пункты меню, чтобы изменить их порядок.
            </div>

            <ul class="b-menu_sortable_level0">
                @foreach($items as $first)
                    <li>
                        @include('admin.client_menu.list_row', ['item'=>$first])
                        @if($first->hasChildren($first->id))
                            <ul class="b-menu_sortable_level1">
                                @foreach($first->getChildren($first->id) as $second)
                                    <li>
                                        @include('admin.client_menu.list_row', ['item'=>$second])
                                    </li>

                                    @if($second->hasChildren($second->id))
                                        <ul class="b-menu_sortable_level2">
                                            @foreach($second->getChildren($second->id) as $third)
                                                <li>
                                                    @include('admin.client_menu.list_row', ['item'=>$third])
                                                </li>
                                            @endforeach
                                        </ul>
                                    @endif
                                @endforeach

                            </ul>
                        @endif
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
@endsection

resources/views/admin/client_menu/list_row.blade.php
<div class="row">
    <div class="b-menu_sortable__title col-lg-10 col-md-10 col-sm-10 col-xs-10">
        <a href="{{route('menu.edit', $item->id)}}">
            {{$loop->iteration}}. {{$item['item_name']}}
        </a>
    </div>
    <div class="b-menu_sortable_btn col-lg-2 col-md-2 col-sm-2 col-xs-2">
        <a class="btn btn-default b-menu_sortable__edit"
           href="{{route('menu.edit', $item->id)}}">
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <form method="POST"
              class="form-inline"
              action="{{route('menu.destroy', $item->id)}}"
              onsubmit="return confirm('Удалить пункт меню?')">

            {{method_field('DELETE')}}
            {{csrf_field()}}

            {{--this field is used for saving items order--}}
            <input type="hidden" name="item_id" value="{{$item->id}}" data-parent="{{$item->parent_id}}">

            <button type="submit" class="btn btn-danger">
                <span class="glyphicon glyphicon-remove"></span>
            </button>
        </form>
    </div>
</div>