routes/web.php
<?php
//client routes
Route::get('/', 'MainPageController@index');

Route::post('/defer/add', 'ProductDeferController@addDeferred');
Route::post('/defer/send', 'ProductDeferController@sendForm');
Route::post('/defer/delete_all', 'ProductDeferController@deleteAll');
Route::get('/defer/delete', 'ProductDeferController@delete');
Route::get('/defer', 'ProductDeferController@defer');

Route::get('news', 'NewsController@showForClient');
Route::get('news/{news}', 'NewsController@showOneForClient');

Route::get('dizajn', 'DesignStudioController@showPage');

//catalog
Route::get('catalog', 'CatalogController@index')->name('catalog.index');
Route::get('catalog/{first}', 'CatalogController@firstLevel');
Route::get('catalog/{first}/{second}', 'CatalogController@secondLevel');
Route::get('catalog/{first}/{second}/{third}', 'CatalogController@thirdLevel');
Route::get('catalog/{first}/{second}/{third}/{product}', 'CatalogController@showProduct');


//ajax calls
Route::group(['prefix' => 'ajax',], function () {
    Route::post('/subscribe', 'SubscriberController@store');
    Route::post('/contact', 'CallbackController@makeFromAjax');
});

//admin login
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('logout', 'Auth\LoginController@logout');
    Auth::routes();
});

//admin routes
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'ClientMenuController@index');

    Route::post('menu/order', 'ClientMenuController@updateOrder')->name('menu.order');
    Route::resource('menu', 'ClientMenuController');

    Route::get('contacts/edit', 'ContactsController@edit')->name('contacts.edit');
    Route::post('contacts/update', 'ContactsController@update')->name('contacts.update');

    Route::get('interior/edit', 'InteriorController@edit')->name('interior.edit');
    Route::post('interior/update', 'InteriorController@update')->name('interior.update');

    Route::get('news/copy/{id}', 'NewsController@copy')->name('news.copy');
    Route::post('news/order', 'NewsController@updateOrder')->name('news.order');
    Route::resource('news', 'NewsController');

    Route::post('photos/ajax', 'PhotosController@uploadAjax');
    Route::post('photos/deleteMulti', 'PhotosController@destroyMulti')->name('photos.delete.multi');
    Route::resource('photos', 'PhotosController');

    Route::any('ajax/imageUpload', 'PhotosController@uploadAjax');
    Route::any('ajax/searchPhoto', 'PhotosController@searchAjax');

    Route::resource('slider', 'Admin\SliderController');
    Route::post('slider/order', 'Admin\SliderController@updateOrder')->name('slider.order');

    Route::resource('info_page', 'InfoPageController');
    Route::resource('meta_data', 'MetaDataController');

    Route::resource('subscriber', 'SubscriberController');

    Route::resource('product', 'ProductController');

    Route::resource('category', 'CategoryController');
    Route::post('category/order', 'CategoryController@updateOrder')->name('category.order');

    Route::resource('order', 'OrderController');

    Route::resource('callback', 'CallbackController');

    Route::post('brand/order', 'BrandController@updateOrder')->name('brand.order');
    Route::resource('brand', 'BrandController');

    Route::group(['prefix' => 'settings'], function () {
        Route::put('settings/offer/update','Admin\Settings\SpecialOfferController@update')->name('settings.offer.update');
        Route::get('settings/offer/edit','Admin\Settings\SpecialOfferController@edit')->name('settings.offer.edit');

    });

    Route::resource('design_studio', 'DesignStudioController');

});

Route::get('/{any}', 'PageController@index')->where('any', '(.*)');

app/Models/MetaData.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class MetaData extends Model
{
    protected $table = 'pages';

    protected $fillable = ['title', 'keywords', 'description'];

    /**
     * Build a query depending on request parameters
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function getQuery()
    {
        $query = $this->newQuery();
        if ($this->getSortColumn()) {
            $query->orderBy($this->getSortColumn(), 'desc');
        }

        if (request()->exists('search_word')) {
            $query->where('title', 'like', '%'.request('search_word').'%');
        }

        return $query;
    }

    /**
     * By what column in the database to sort results
     *
     * @return bool|string
     */
    private function getSortColumn()
    {
        $sort = request('sort');

        if ($sort == '1') return 'created_at';
        if ($sort == '2') return 'updated_at';
        if ($sort == '3') return 'title';

        return false;
    }

}

app/Http/Controllers/MetaDataController.php
<?php

namespace App\Http\Controllers;

use App\Models\MetaData;

class MetaDataController extends Controller
{

    protected $perPage = '20';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pages = (new MetaData)
            ->getQuery()
            ->paginate($this->perPage)
            ->appends(
                ['search_word' => request('search_word'),
                 'sort'        => request('sort')
                ]
            );

        $lastPageNum = $pages->currentPage() * $pages->perPage() - ($this->perPage - 1);
        $req = request();

        return view('admin.meta_data.list', compact('pages', 'lastPageNum', 'req'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page = MetaData::findOrFail($id);

        return view('admin.meta_data.edit', compact('page'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id Page id
     * @return \Illuminate\Http\Response
     */
    public function update($id)
    {
        $page = MetaData::findOrFail($id);
        $page->fill(request()->all());
        $page->save();

        flash('Метаданные обновлены')->important();

        return redirect()->route('meta_data.index');
    }

}

resources/views/admin/meta_data/edit.blade.php
@extends('admin.app')

@section('content')
    <div class="panel panel-default b-info-page">
        <div class="panel-heading">Редактировать метаданные</div>

        <div class="panel-body">
            <form method="POST"
                  action="{{route('meta_data.update', $page->id)}}">
                <div class="form-group">
                    <label for="title">Заглавие</label>
                    <input type="text" name="title" id="title" class="form-control" value="{{ $page->title }}">
                </div>

                <div class="form-group">
                    <label for="keywords">Ключевые слова</label>
                    <input type="text" name="keywords" id="keywords" class="form-control"
                           value="{{ $page->metadata ? $page->metadata->keywords : '' }}">
                </div>

                <div class="form-group">
                    <label for="description">Описание</label>
                    <textarea name="description" id="description" rows="5"
                              class="form-control">{{ $page->metadata ? $page->metadata->description: '' }}</textarea>
                </div>

                {{method_field('PUT')}}
                {{csrf_field()}}

                <button type="submit" class="btn btn-default">Обновить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/meta_data/list.blade.php
@extends('admin.app')
@inject('pageObj', 'App\Models\Page')

@section('content')
    <div class="panel panel-default b-meta-data">
        <div class="panel-heading">Метаданные страниц</div>

        <div class="panel-body">

            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="row">
                    <form method="GET" class=" form-inline"
                          action="{{route('meta_data.index')}}">
                        <div class="form-group">
                            <input type="text"
                                   placeholder="Поиск по заглавию."
                                   name="search_word"
                                   id="search_word"
                                   class="form-control"
                                   value="{{ request('search_word') }}">
                        </div>
                        <input type="hidden" name="sort" value="{{request('sort')}}">
                        <button type="submit" class="btn btn-primary">Поиск</button>
                    </form>
                    <form method="GET"
                          class="form-inline"
                          action="{{route('meta_data.index')}}">
                        <div class="form-group">
                            <select name="sort" id="sort" class="form-control">
                                <option value="1"
                                        {{ array_key_exists('sort', $req) && $req['sort'] == 1 ? "selected" : '' }}>
                                    Дате создания
                                </option>
                                <option value="2" {{ array_key_exists('sort', $req) && $req['sort'] == 2 ? "selected" : '' }}>
                                    Дате изменения
                                </option>
                                <option value="3" {{ array_key_exists('sort', $req) && $req['sort'] == 3 ? "selected" : '' }}>
                                    Заглавию
                                </option>
                            </select>
                        </div>
                        <input type="hidden" name="search_word" value="{{request('search_word')}}">
                        <button type="submit" class="btn btn-primary">Сортировать</button>
                    </form>

                </div>
            </div>


            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Тип</th>
                    <th>Заглавие</th>
                    <th>Ключ.сл.</th>
                    <th>Описание</th>
                </tr>
                </thead>
                <tbody>

                @foreach($pages as $index=>$page)
                    <tr>
                        <td class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                            {{$lastPageNum + $index}}
                        </td>
                        <td>{{$pageObj->getTypeName($page->type)}}</td>
                        <td><a href="{{route('meta_data.edit', $page->id)}}">{{$page->title}}</a></td>
                        <td>{{$page->keywords}}</td>
                        <td>{{$page->description}}</td>
                    </tr>
                @endforeach

                </tbody>
            </table>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                {{ $pages->links() }}
            </div>

        </div>
    </div>
@endsection